name: check-oam

on: [push]

jobs:
  check:
    name: Check '${{ matrix.target }}' in '${{ matrix.oam }}'
    strategy:
      fail-fast: false
      matrix:

        # [BUILD]: all build targets
        target:
          - Release
          - ""

        # [REF]: same commit and (newest on) branch
        restore_branch:
          - false
          # TODO include again:
          # - true

    uses: openknx/actions/.github/workflows/openknx-oam-check.yml@v0
    with:
      # use repo-name and ref as defaults

      restore_branch: ${{ matrix.restore_branch }}
      target: ${{ matrix.target }}
      KNXPROD_PREFIX: InternetServices
